source "https://rubygems.org"

ruby "3.0.2"

gem "rails", "~> 7.1.6"
gem "sprockets-rails"
gem "sqlite3", "~> 1.7"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"

# SSH provisioning
gem "net-ssh", "~> 7.2"
gem "net-scp", "~> 4.0"

# Background jobs
gem "solid_queue", "~> 0.3"

# QR code generation for enrollment tokens
gem "rqrcode", "~> 2.2"

# Encryption for SSH keys at rest
gem "lockbox", "~> 1.3"

# OmniAuth for IdP-based enrollment
gem "omniauth", "~> 2.1"
gem "omniauth-rails_csrf_protection", "~> 1.0"
gem "omniauth-google-oauth2", "~> 1.1"
gem "omniauth_openid_connect", "~> 0.7"

gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]
# Pin transitive deps compatible with Ruby 3.0
gem "psych", "~> 4.0"
gem "rdoc", "~> 6.5"
gem "irb", "~> 1.10"

gem "bootsnap", require: false

group :development do
  gem "web-console", "~> 4.2"
end

group :test do
  gem "minitest", "~> 5.20"
  gem "mocha", "~> 2.1"
end
