defmodule ZtlpRelay.ClientRouteProdHmacTest do
  use ExUnit.Case, async: false

  @moduledoc """
  Prod-mode HMAC contract between the Rust client and this relay
  (2026-09-13, cloud-demo follow-up 4).

  With `ZTLP_RELAY_HMAC_MODE=prod` + `ZTLP_RELAY_REGISTRATION_SECRET=<64 hex>`:
    * a CLIENT_ROUTE signed by the Rust client (`ztlp agent` with
      `[tunnel] relay_secret`, or `ztlp connect --relay-secret`) MUST install
      the client -> gateway route;
    * the same frame with a zero HMAC MUST be rejected (no ETS write);
    * a frame signed with the hex STRING instead of the decoded 32 bytes MUST
      be rejected (this is the gateway-side bug fixed in
      `ZtlpGateway.RelayRegistrar.legacy_secret/0`).

  The HMAC algorithm is cross-checked against a vector generated by the Rust
  side (`proto/tests/client_route_signed_vector_test.rs` writes
  `test/fixtures/client_route_signed_vector.json`).
  """

  alias ZtlpRelay.UdpListener

  @fixture Path.expand("../fixtures/client_route_signed_vector.json", __DIR__)
  @secret_hex "03949c364265e5e2cf0eb0f90a27cf51b97e85c2564a9ece899d6daab2a70d7c"

  defp fixture_field(name) do
    body = File.read!(@fixture)
    [_, v] = Regex.run(~r/"#{name}":\s*"?([^",\n]+)"?/, body)
    v
  end

  defp build_client_route(node_id, service_name, ts, key_or_nil) do
    signed =
      <<0x0B, node_id::binary-size(16), byte_size(service_name)::8, service_name::binary,
        ts::64-signed>>

    hmac =
      case key_or_nil do
        nil -> <<0::256>>
        key -> :crypto.mac(:hmac, :sha256, key, signed)
      end

    <<0x5A, 0x37, signed::binary, hmac::binary>>
  end

  setup do
    prev_mode = System.get_env("ZTLP_RELAY_HMAC_MODE")
    prev_secret = System.get_env("ZTLP_RELAY_REGISTRATION_SECRET")
    System.put_env("ZTLP_RELAY_HMAC_MODE", "prod")
    System.put_env("ZTLP_RELAY_REGISTRATION_SECRET", @secret_hex)

    on_exit(fn ->
      for {k, v} <- [{"ZTLP_RELAY_HMAC_MODE", prev_mode}, {"ZTLP_RELAY_REGISTRATION_SECRET", prev_secret}] do
        if v, do: System.put_env(k, v), else: System.delete_env(k)
      end
    end)

    if :ets.info(:ztlp_forwarded_quic_tuples, :name) != :undefined do
      :ets.delete_all_objects(:ztlp_forwarded_quic_tuples)
    end

    case GenServer.whereis(ZtlpRelay.GatewayForwarder) do
      nil -> {:ok, _} = ZtlpRelay.GatewayForwarder.start_link()
      _ -> :ok
    end

    ZtlpRelay.GatewayForwarder.clear_all()

    gw_node_id = :crypto.strong_rand_bytes(16)
    gw_addr = {{10, 0, 0, 77}, 23097}
    ZtlpRelay.GatewayForwarder.register_dynamic_gateway(gw_addr, gw_node_id, "demo-dashboard", 60)
    Process.sleep(20)

    %{gw_addr: gw_addr}
  end

  test "fixture: relay-decoded secret reproduces the Rust client's HMAC byte-for-byte" do
    assert fixture_field("secret_hex") == @secret_hex
    frame = Base.decode16!(fixture_field("frame_signed_hex"), case: :lower)
    node_id = Base.decode16!(fixture_field("node_id_hex"), case: :lower)
    ts = String.to_integer(fixture_field("timestamp"))

    [key] = ZtlpRelay.HmacSecrets.verifying_secrets("demo-dashboard") ++
              [ZtlpRelay.HmacSecrets.legacy_secret()] |> Enum.reject(&is_nil/1) |> Enum.take(1)

    assert byte_size(key) == 32
    assert build_client_route(node_id, "demo-dashboard", ts, key) == frame

    <<0x5A, 0x37, signed::binary-size(byte_size(frame) - 34), hmac::binary-size(32)>> = frame
    assert {:ok, :legacy} = ZtlpRelay.HmacSecrets.verify("demo-dashboard", signed, hmac)
  end

  test "prod mode: signed CLIENT_ROUTE installs the route", %{gw_addr: gw_addr} do
    port = UdpListener.get_port()
    {:ok, client} = :gen_udp.open(0, [:binary])
    {:ok, client_port} = :inet.port(client)
    sender = {{127, 0, 0, 1}, client_port}

    key = Base.decode16!(@secret_hex, case: :lower)
    pkt = build_client_route(:crypto.strong_rand_bytes(16), "demo-dashboard", System.system_time(:second), key)
    :gen_udp.send(client, {127, 0, 0, 1}, port, pkt)
    Process.sleep(50)

    assert [{{:client_map, ^sender}, {^gw_addr, _}}] =
             :ets.lookup(:ztlp_forwarded_quic_tuples, {:client_map, sender})

    :gen_udp.close(client)
  end

  test "prod mode: zero-HMAC CLIENT_ROUTE is rejected" do
    port = UdpListener.get_port()
    {:ok, client} = :gen_udp.open(0, [:binary])
    {:ok, client_port} = :inet.port(client)
    sender = {{127, 0, 0, 1}, client_port}

    pkt = build_client_route(:crypto.strong_rand_bytes(16), "demo-dashboard", System.system_time(:second), nil)
    :gen_udp.send(client, {127, 0, 0, 1}, port, pkt)
    Process.sleep(50)

    assert :ets.lookup(:ztlp_forwarded_quic_tuples, {:client_map, sender}) == []
    :gen_udp.close(client)
  end

  test "prod mode: CLIENT_ROUTE signed with the undecoded hex string is rejected" do
    port = UdpListener.get_port()
    {:ok, client} = :gen_udp.open(0, [:binary])
    {:ok, client_port} = :inet.port(client)
    sender = {{127, 0, 0, 1}, client_port}

    pkt =
      build_client_route(:crypto.strong_rand_bytes(16), "demo-dashboard", System.system_time(:second), @secret_hex)

    :gen_udp.send(client, {127, 0, 0, 1}, port, pkt)
    Process.sleep(50)

    assert :ets.lookup(:ztlp_forwarded_quic_tuples, {:client_map, sender}) == []
    :gen_udp.close(client)
  end
end
